bridges/urls.py
from django.conf.urls import include, url
# from django.contrib import admin
from djgeojson.views import TiledGeoJSONLayerView, GeoJSONLayerView
from erm.settings import RootModel
from erm.views import base, geo

urlpatterns = [
    url(r'^karte/', base.show_map),
    url(r'^tilegeojson/(?P<z>\d+)/(?P<x>\d+)/(?P<y>\d+).geojson$',
        TiledGeoJSONLayerView.as_view(model=RootModel), name='tilegeojson'),
    url(r'^map/(?P<min_lon>[0-9.]+)/(?P<min_lat>[0-9.]+)/(?P<max_lon>[0-9.]+)/(?P<max_lat>[0-9.]+)/(?P<zoom>[0-9]+)$',
        geo.map_cutout),
    url(r'^data.geojson$', GeoJSONLayerView.as_view(model=RootModel), name='data'),
    url(r'^(.+)', include('erm.urls')),
    url(r'^', base.index),
]

erm/urls.py
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  2 21:10:10 2014

@author: simonwoerpel
"""

from django.conf.urls import url
from erm.views.base import DynamicDetailView


urlpatterns = [
    url(r'^', DynamicDetailView.as_view()),
]

app/models.py
# -*- coding: utf-8 -*-
"""
Created on Tue Sep  2 19:25:09 2014

@author: simonwoerpel

models for bridges app

inspired by http://www.zeit.de/mobilitaet/2014-09/deutsche-bahn-bruecken-zustand
info: http://blog.zeit.de/open-data/2014/09/02/deutsche-bahn-bruecken-daten/
data: https://docs.google.com/spreadsheets/d/1z2zpPexIcGagV9qGeeIRct0u5BfMOdHut6vKl2nY8rk/edit#gid=252127531

"""

from django.db import models
from django.contrib.gis.db import models as gismodels
from django.contrib.sites.models import Site
from erm.models import AbstractNameSlugModel
from erm import geoutils

# Create your models here.


class DataRaw(models.Model):
    segment = models.CharField('Netzsegment', max_length=200)
    route = models.CharField('Streckennr', max_length=4)
    status = models.CharField('Zustandskategorie', max_length=1)
    state = models.CharField('Bundesland', max_length=200)
    lon = models.CharField('Lon', max_length=50)
    lat = models.CharField('Lat', max_length=50)

    class Meta:
        verbose_name = 'Brücke'
        verbose_name_plural = 'Brücken'

    def __unicode__(self):
        return '%s, %s - %s' % (self.state, self.segment, self.route)


class State(AbstractNameSlugModel):
    class Meta:
        verbose_name = u'Bundesland'
        verbose_name_plural = u'Bundesländer'
        ordering = ['name']


class Status(AbstractNameSlugModel):
    bootstrap_flag = models.CharField('Bootstrap Farbe', max_length=50,
                                      blank=True, null=True)
    description = models.CharField('Anmerkungen', max_length=200,
                                   blank=True, null=True)

    class Meta:
        verbose_name = u'Zustandskategorie'
        verbose_name_plural = u'Zustandskategorien'
        ordering = ['name']


class Route(AbstractNameSlugModel):
    class Meta:
        verbose_name = u'Strecke'
        verbose_name_plural = u'Strecken'
        ordering = ['name']


class Segment(AbstractNameSlugModel):
    class Meta:
        verbose_name = u'Netzsegment'
        verbose_name_plural = u'Netzsegmente'
        ordering = ['name']


class Bridge(gismodels.Model):
    slug = models.SlugField('Slug', unique=True, db_index=True)
    segment = gismodels.ForeignKey(Segment, verbose_name='Netzsegment')
    route = gismodels.ForeignKey(Route, verbose_name='Streckennummer')
    state = gismodels.ForeignKey(State, verbose_name='Bundesland')
    status = gismodels.ForeignKey(Status, verbose_name='Zustandskategorie')
    geom = gismodels.PointField()

    objects = gismodels.GeoManager()

    def __unicode__(self):
        return u'%s, %s - %s' % (self.state, self.segment, self.route)

    def get_leaflet(self):
        return geoutils.get_leaflet(self)

    def get_googlemap(self):
        return geoutils.get_googlemap(self)

    def get_json(self):
        return geoutils.get_json(self)

    def get_absolute_url(self):
        return u'https://' + Site.objects.get_current().domain + \
            u'/bruecke:%s/' % self.slug

    class Meta:
        verbose_name = 'Eisenbahnbrücke'
        verbose_name_plural = 'Eisenbahnbrücken'

erm/models.py
from django.db import models
from django.utils.text import slugify
from django.contrib.sites.models import Site


# Create your models here.


class AbstractNameSlugModel(models.Model):
    name = models.CharField('Name', max_length=200)
    slug = models.SlugField('Slug', max_length=200)

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return u'https://' + Site.objects.get_current().domain + u'/%s:%s/' % \
            (slugify(self._meta.verbose_name), self.slug)

erm/views/base.py
# -*- coding: utf-8 -*-

from django.shortcuts import render
from django.views.generic import ListView, DetailView
from erm.views.dynamic import BaseFilterView
from erm.settings import RootModel


class DynamicDetailView(DetailView):

    context_object_name = 'object'

    def get_object(self):
        return BaseFilterView(self.request.path).get_object()

    def get_context_data(self, **kwargs):
        context = super(DynamicDetailView, self).get_context_data(**kwargs)
        for extra_context in BaseFilterView(self.request.path) \
                .get_context_data():
            context[extra_context[0]] = extra_context[1]

        return context

    def get_template_names(self):
        return BaseFilterView(self.request.path).get_template_names()


class RootModelList(ListView):
    model = RootModel


def index(request):
    return render(request, 'erm/index.html')


def show_map(request):
    return render(request, 'erm/geo/map.html')

erm/views/charts.py
# -*- coding: utf-8 -*-
"""
Created on Sat Aug 16 14:52:35 2014

@author: simonwoerpel

"""


from django.db.models import Sum, Avg, Count
from django.template.loader import render_to_string
from django.utils.text import slugify
from erm.utils import get_statistic_data_for_filter, get_queryset_for_instance
from erm import settings
from erm.settings import RootModel


class DynamicChart(object):
    '''gives charts x and y data for instance
    aggr -- str'''

    def __init__(self, queryset, model, aggr):
        self.queryset = queryset
        self.model = model
        self.aggr = aggr

    def get_chart_data(self):
        '''wraps `app.erm.get_statistic_data_for_filter()` into xdata ydata
        for nvd3-charts
        model -- model to user as filter in queryset
        aggr -- str, which aggregator to use
        '''

        data = get_statistic_data_for_filter(self.model, self.queryset)
        xdata = [d['instance'].name for d in data]
        ydata = [d['value'] for da in data
                for d in da['data'] if d['name'] == self.aggr]

        return xdata, ydata

    def render_nvd3_js(self, charttype='pieChart',
               extra=settings.STANDARD_CHART_EXTRA,
               chartcontainer=settings.STANDARD_CHART_CONTAINER):
        '''renders js data for chart'''

        xdata, ydata = self.get_chart_data()

        template = u'charts/%s_js.html' % slugify(unicode(charttype))

        data = {
            'chartdata': {'x': xdata, 'y': ydata, },
            'charttype': charttype,
            'chartcontainer': chartcontainer,
            'extra': extra,
        }

        return render_to_string(template, data)

    def render_nvd3_div(self, extra_content=None, charttype='pieChart',
                        chartcontainer=settings.STANDARD_CHART_CONTAINER):
        '''renders div container for chart'''

        template = u'charts/%s_div.html' % slugify(unicode(charttype))

        data = {
            'chartcontainer': chartcontainer,
            'extra_content': extra_content,
        }

        return render_to_string(template, data)


def get_charts_for_instance(instance):
    '''returns list of rendered charts for instance based on queryset
    '''

    queryset = get_queryset_for_instance(instance)

    js = []
    divs = []

    for model in settings.FILTER_MODELS:
        if not model == instance._meta.model:
            for aggr in settings.AGGREGATOR_LIST:
                container = u'%s_%s' % (model.__name__, aggr.__name__)
                headline = u'%s (%s)' % (model._meta.verbose_name_plural,
                                              aggr.__name__)
                teaser = u'%s nach %s mit %s: %s' % \
                    (unicode(RootModel._meta.verbose_name_plural),
                     unicode(model._meta.verbose_name_plural),
                     unicode(instance._meta.verbose_name), instance)
                extra_content = '<h4>%s</h4><p>%s</p>' % (headline, teaser)
                chart = DynamicChart(queryset, model, aggr.__name__)
                js += [chart.render_nvd3_js(chartcontainer=container)]
                divs += [chart.render_nvd3_div(chartcontainer=container,
                                               extra_content=extra_content)]

    return js, divs


class DynamicTimeChart(object):
    '''returns a Line Chart based on Time devlopement
    TODO: not abstract yet
    '''

    def __init__(self, field=False, date_group='year',
                 queryset=RootModel.objects.all()):

        if not field:
            raise Exception('field must be set')

        self.field = field
        self.date_group = date_group
        self.queryset = queryset
        self.charttype = 'linePlusBarChart'

    def get_chart_data(self):
        '''returns xdata, ydata1, ydata2'''
        extra_queryset = 'EXTRACT (%s FROM %s)' % (self.date_group,
                                                   self.field)
        data = RootModel.objects \
            .extra({'year': extra_queryset}) \
            .values('year').annotate(n=Count('id'), power=Sum('power'),
                                     power_avg=Avg('power')) \
            .order_by('year')

        xdata = [int(year['year']) for year in data]
        ydata1 = [int(year['n']) for year in data]
        # this has to be abstract...
        ydata2 = [round(year['power'], 1) for year in data]

        return xdata, ydata1, ydata2

    def render_chart(self):
        xdata, ydata1, ydata2 = self.get_chart_data()
        kwargs2 = {'bar': True}

        chartdata = {
            'x': xdata,
            'name1': 'Neue Anlagen', 'y1': ydata1, 'extra1': '',
            'name2': 'Summe kWh neue Anlagen', 'y2': ydata2, 'extra2': '', 'kwargs2': kwargs2,
        }

        data = {
            'charttype': self.charttype,
            'chartdata': chartdata,
            'chartcontainer': 'index_timechart',
            'extra': {'x_is_date': True,
                      'x_axis_format': '%Y'}
        }

        div = render_to_string('charts/chart_div.html', data)
        js = render_to_string('charts/timechart_js.html', data)
        return div, js

erm/views/dynamic.py
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 14 20:56:23 2014

@author: simonwoerpel

"""


from django.http import Http404
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.contenttypes.models import ContentType
from erm.settings import MODEL_LOOKUPS, RootModel
from erm.utils import get_queryset_for_instance
# from erm.views.charts import get_charts_for_instance


class BaseFilterView(object):
    '''delivers required arguments for `app.views.base.DynamicListView` based
    on the given `url`
    '''

    def __init__(self, url):
        '''urls have to be in format like '/model1:instance1/model2:instance2/
        '''
        try:
            url = url.replace('/', '')
            model, instance = url.split(':')
        except:
            raise Http404

        try:
            self.model = ContentType.objects.get(model__iexact=model)
        except ContentType.DoesNotExist:
            try:
                model_name = MODEL_LOOKUPS[model]
            except KeyError:
                raise Http404

            self.model = ContentType.objects.get(model=model_name)

        try:
            self.instance = self.model.get_object_for_this_type(slug=instance)
        except ObjectDoesNotExist:
            raise Http404

        self.queryset = get_queryset_for_instance(self.instance) \
            if not self.model.model_class() == RootModel else None
        self.template_name = 'erm/dynamic_detail.html' \
            if not self.model.model_class() == RootModel \
            else 'app/bridge_detail.html'

    def get_template_names(self):
        return [self.template_name, ]

    def get_object(self):
        '''returns the actual object instance'''
        return self.instance

    def get_context_data(self):
        '''returns extra context for given view'''
        #chart_js, chart_divs = get_charts_for_instance(self.instance)
        return [
            ['object_name', self.get_object()._meta.verbose_name, ],
        #    ['chart_js', chart_js, ],
        #    ['chart_divs', chart_divs, ],
        ]

erm/views/geo.py
# -*- coding: utf-8 -*-
"""
Created on Thu Aug 21 19:31:34 2014

@author: simonwoerpel

geo specific views

TODO: not abstract yet
"""

from django.http import JsonResponse
from django.contrib.gis.geos import Polygon
from erm.settings import RootModel


def map_cutout(request, min_lon, min_lat, max_lon, max_lat, zoom):
    '''returns the `RootModel` instances based on bbox for json leaflet'''
    if not int(zoom) > 12:
        return JsonResponse(None, safe=False)
    else:
        bbox = (float(min_lon), float(min_lat), float(max_lon), float(max_lat))
        box = Polygon.from_bbox(bbox)
        q = RootModel.objects.filter(geom__within=box)
        resp = [p.get_json() for p in q]
        return JsonResponse(resp, safe=False)

erm/templates/erm/dynamic_detail.html
{% extends 'app.html' %}

{% load dynamic_view_tags %}

{% block title %}
    {{ object_name }}: {{ object.name }}
{% endblock title %}


{% block extra_js %}
    {% for js in chart_js %}
        {{ js }}
    {% endfor %}
{% endblock %}

{% block app %}

<div class="row">
    <h1>{{ object_name }}: {{ object }}</h1>
    <p>{{ object_type }}</p>
    <div class="col-sm-6">
        <p><strong>Daten</strong></p>
        {% get_table_for_instance object %}
    </div>
    <div class="col-sm-6">
        {% get_other_instances object 20 %}
    </div>
</div>
<div class="row">
    {% comment %}
        <h1>Diagramme</h1>
        {% for chart in chart_divs %}
            <div class="col-sm-4">{{ chart }}</div>
        {% endfor %}
    {% endcomment %}
    <div class="col-md-12">
        <h1>Die Brücken</h1>
        {% object_table object %}
    </div>
</div>

{% endblock %}

erm/templates/erm/index.html
{% extends 'base.html' %}

{% load static dynamic_view_tags %}

{% block menu %}
    
{% endblock menu %}

{% block title %}
    Startseite
{% endblock title %}

{% block extra_css %}
<link rel="stylesheet" href="{% static 'theme/css/index.css' %}" />
{% endblock %}


{% block extra_js %}


{% endblock %}


{% block content %}

    <!-- Full Width Image Header -->
    <header class="header-image">
        <div class="headline">
            <div class="container">
                <h1>Marode Brücken</h1>
                <h2><a href="#ueber">in der Satellitenansicht</span></a></h2>
            </div>
        </div>
    </header>

    <!-- Page Content -->
    <div class="container">

        <hr class="featurette-divider">

        <!-- First Featurette -->
        <div class="featurette" id="ueber">
            <img class="featurette-image img-circle img-responsive pull-right" src="{% static 'theme/img/marode.png' %}">
            <h2 class="featurette-heading">Rostige Brücken,
                <span class="text-muted">verständliche Daten.</span>
            </h2>
            <p class="lead">...dank <a href="http://zeit.de">Zeit Online</a>, möchte man sagen. Denn die werten Kollegen haben über die <a href="http://www.zeit.de/mobilitaet/2014-09/deutsche-bahn-bruecken-zustand">maroden Brücken der Bahn</a> recherchiert und dabei <a href="https://docs.google.com/spreadsheets/d/1z2zpPexIcGagV9qGeeIRct0u5BfMOdHut6vKl2nY8rk/edit#gid=252127531">ihren wunderbaren Datensatz</a> gleich noch der Allgemeinheit zur Verfügung gestellt. Damit wir nicht das gleiche Problem wie die Zeit-Redakteure haben, <a href="http://blog.zeit.de/open-data/2014/09/02/deutsche-bahn-bruecken-daten/">die die Daten relativ mühsam und aufwendig zusammentragen mussten</a>. Das ist richtig Open Data und sehr fair von euch.</p>
            <p class="lead">
                <a href="http://twitter.com/simonwoerpel">Mich</a> hatte dann schnell interessiert, wie die maroden Brücken wohl von oben aussehen, und dank Google Maps ist das ja heutzutage kein Problem. Ein bisschen <a href="http://djangoproject.com">Django</a> und <a href="http://leafletjs.com">leaflet.js</a> und – ach ja, das hässliche Bootstrap-Standard-Design – und schon ist jede Brücke aus der Satellitenperspektive zu sehen. Zugegeben, ich hatte mir mehr Rost erhofft.
            </p>
            <p class="lead">
                Ich freue mich über <a href="mailto:simon.woerpel@gmail.com">Tipps und Anregungen</a> jeder Art.</p>
        </div>
        <div class="row" id="bruecken">
            <div class="col-md-12">
            <h1>Ein paar zufällig ausgewählte Eisenbahnbrücken.</h1>
            <p class="lead">Oder direkt zur <a href="/karte/">Karte</a>.</p>
            {% object_table random=True %}
            </div>
        </div>

        
        
        <hr class="featurette-divider">

</div>



{% endblock content %}

erm/templates/erm/instance_table.html
<table class="table table-stripped">

{% if landscape %}

    <thead>
        <tr>
        {% for field in fields %}
            <th>{{ field.name }}</th>
        {% endfor %}
        </tr>
    </thead>
    
    <tbody>
        <tr>
        {% for field in fields %}
            <td>{{ field.value }}</td>
        {% endfor %}
        </tr>
    </tbody>
    

{% else %}
    {% for field in fields %}
    <tr>
        <th>{{ field.name }}</th>
        <td>{{ field.value|default_if_none:"" }}</td>
    </tr>
    {% endfor %}
    
{% endif %}
    
</table>

erm/templates/erm/menu.html
<div class="navbar navbar-default navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Start</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="/karte/">Karte</a></li>
            <!--<li><a href="#about">About</a></li>
            <li><a href="#contact">Contact</a></li>-->
              {% for parent in parents %}
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ parent.name }} <span class="caret"></span></a>
                  <ul class="dropdown-menu" role="menu">
                      {% for child in parent.children %}
                        <li><a href="{{ child.get_absolute_url }}">{{ child }}</a></li>
                      {% endfor %}
                  </ul>
                </li>
              {% endfor %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

erm/templates/erm/object_table.html
<div>
    <p class="small">Seite {{ objects.number }} von {{ objects.paginator.num_pages }}.</p>
    <ul class="pager">
        {% if objects.has_previous %}
            <li><a href="?p={{ objects.previous_page_number }}">zurück</a></li>
        {% endif %}

        {% if objects.has_next %}
            <li><a href="?p={{ objects.next_page_number }}">vor</a></li>
        {% endif %}
    </ul>
</div>
<table class="table table-stripped">
    <thead>
        <tr>
            <th>Zustand</th><th>Bundesland</th><th>Netzsegment</th><th>Strecke</th><th></th>
        </tr>
    </thead>
    <tbody>
        {% for object in objects %}
            <tr class="{{ object.status.bootstrap_flag }}">
                <td>
                    <span class="label label-{{ object.status.bootstrap_flag }}">
                        {{ object.status }}
                    </span> 
                </td>
                <td>
                    <a href="{{ object.state.get_absolute_url }}">{{ object.state }}</a> 
                </td>
                <td>
                    <a href="{{ object.segment.get_absolute_url }}">{{ object.segment }}</a> 
                </td>
                <td>
                    <a href="{{ object.route.get_absolute_url }}">{{ object.route }}</a> 
                </td>
                <td>
                    <span class="fa fa-toggle-right"></span>
                    <a href="{{ object.get_absolute_url }}">Ansehen</a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
<div>
    <p class="small">Seite {{ objects.number }} von {{ objects.paginator.num_pages }}.</p>
    <ul class="pager">
        {% if objects.has_previous %}
            <li><a href="?p={{ objects.previous_page_number }}">zurück</a></li>
        {% endif %}

        {% if objects.has_next %}
            <li><a href="?p={{ objects.next_page_number }}">vor</a></li>
        {% endif %}
    </ul>
</div>

erm/templates/erm/other_instances.html
<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#other_instances">
          <strong>Andere {{ name_plural }}</strong>
        </a>
          <span class="fa fa-toggle-down"></span>
      </h4>
    </div>
    <div id="other_instances" class="panel-collapse collapse">
      <div class="panel-body">
        <table class="table table-stripped">
            <tbody>
                {% for instance in instances %}
                    <tr><td><a href="{{ instance.get_absolute_url }}">{{ instance.name }}</a> 
                        <span class="badge">{{ instance.bridge_set.count }}</span></td></tr>
                {% endfor %}
            </tbody>
        </table>
      </div>
    </div>
  </div>
</div>